### PR TITLE
Streaming upload

### PR DESCRIPTION
**Pull request by krukid**
Hi, here's a bare minimum patch that implements Item#store, like the Object#store in the aws-s3 gem

### CODE REVIEW

**Comment by joaodrp** [comment]
Good stuff!

**Comment by joaodrp** [comment]
Any way to get this merged anytime soon?

**Comment by krukid** [comment]
Doesn't look like it.

If you need this in your project, I suggest pulling my fork and bundling it as a local gem, e.g.
`echo 'gem "happening", "0.2.6", :path=>"vendor/gems/happening"' >> your-project-name/Gemfile`.

Just remember to `rm -rf vendor/gems/happening/.git` before committing.

**Comment by igrigorik** [comment]
Any reason why it's not going to get merged?

**Comment by jweiss** [comment]
because it doesn't have any tests :-(

**Pull request closed without merging**
